In [1]:
import numpy as np

data = np.array([[2.2, 5.9, -1.8], [5.4, -3.2, -5.1], [-1.9, 4.2, 3.2]])

In [3]:
from sklearn import preprocessing

bindata = preprocessing.Binarizer(threshold=1.5).transform(data)
print(bindata)

[[1. 1. 0.]
 [1. 0. 0.]
 [0. 1. 1.]]


In [4]:
print('mean', data.mean(axis=0))
print('std dev', data.std(axis=0))

mean [ 1.9         2.3        -1.23333333]
std dev [2.98775278 3.95052739 3.41207008]


In [5]:
scaled_data = preprocessing.scale(data)

print('mean', scaled_data.mean(axis=0))
print('std dev', scaled_data.std(axis=0))

mean [0.00000000e+00 0.00000000e+00 7.40148683e-17]
std dev [1. 1. 1.]


In [7]:
minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_minax = minmax_scaler.fit_transform(data)

print(data_minax)

[[0.56164384 1.         0.39759036]
 [1.         0.         0.        ]
 [0.         0.81318681 1.        ]]


In [9]:
data_l1 = preprocessing.normalize(data, norm='l1')
data_l2 = preprocessing.normalize(data, norm='l2')

print(data_l1)
print()
print(data_l2)

[[ 0.22222222  0.5959596  -0.18181818]
 [ 0.39416058 -0.23357664 -0.37226277]
 [-0.20430108  0.4516129   0.34408602]]

[[ 0.3359268   0.90089461 -0.2748492 ]
 [ 0.6676851  -0.39566524 -0.63059148]
 [-0.33858465  0.74845029  0.57024784]]
